#!/bin/bash
# Simple shell script to set up LAYNII module in user's workspace

# Check that work is actually /storage/work/${USER}
if [ ! -L ${HOME}/work ]; then
    echo "Creating symlink to /storage/work/${USER}"
    tar -czvf ${HOME}/fake_work.tar.gz ${HOME}/work
    ln -s /storage/work/${USER} ${HOME}/work
fi

# Create work/sw if it doesn't exist
if [[ ! -d ${HOME}/work/sw && -L ${HOME}/work ]]; then
    echo "Creating ${HOME}/work/sw"
    mkdir -p ${HOME}/work/sw
fi

if [ ! -d ${HOME}/work/sw/LAYNII ]; then
    mkdir -p ${HOME}/work/sw/LAYNII
fi

# Pull down laynii container
echo "Downloading LAYNII container"
`which singularity` pull --dir=${HOME}/work/sw/LAYNII library://nucci/default/laynii

# Create modules directory under sw
if [ ! -d ${HOME}/work/sw/modules ]; then
    mkdir -p ${HOME}/work/sw/modules
fi

# Move module file to laynii directory under modules
mkdir -p ${HOME}/work/sw/modules/laynii
cp ./1.5.6.lua ${HOME}/work/sw/modules/laynii/1.5.6.lua

# Adjust permissions accordingly
chmod -R ug+rx ${HOME}/work/sw

echo "Installation of the LAYNII module has finished"
echo -e "\nTo use LAYNII, enter the following commands in your terminal:\n"
echo "module use ${HOME}/work/sw/modules"
echo "module load laynii"
echo -e "\nIf you run into any issues please contact Jason at iask@ics.psu.edu"
