#!/bin/bash
# $1 is the location where the user desires to
# have R installed

# Load gcc/7.3.1
module load gcc/7.3.1

# The directory R is going to be installed under
BASE=$1

# The directory that contains all of R dependencies, libraries, etc.
if [ ! -d ${BASE}/R ]; then
    mkdir -p ${BASE}/R
    R_BASE=${BASE}/R
else
    mkdir -p ${BASE}/R-4.0.2
    R_BASE=${BASE}/R-4.0.2
fi

# Create temp directory that will contain all sources
mkdir -p ${R_BASE}/tmp
R_TMP=${R_BASE}/tmp

# Download R 4.0.2 and RPM that contains dependencies
echo "Downloading source files"
cd ${R_TMP}
wget https://cran.r-project.org/src/base/R-4/R-4.0.2.tar.gz
wget http://springdale.math.ias.edu/data/puias/computational/6/SRPMS/R-3.4.3-1.sdl6.src.rpm

if [[ ! -f R-4.0.2.tar.gz || ! -f R-3.4.3-1.sdl6.src.rpm ]]; then
    echo "Something went wrong downloading source files"
    echo "Please contact iask@ics.psu.edu for assistance"
    exit
fi

# Extract files from rpm file
rpm2cpio R-3.4.3-1.sdl6.src.rpm | cpio -idmv

mkdir -p ${R_TMP}/build

# Extract source files and store them in build
echo "Extracting and uncompressing source files"
tar -xzvf bzip2-1.0.6.tar.gz -C build
tar -xjvf curl-7.56.1.tar.bz2 -C build
tar -xjvf pcre-8.41.tar.bz2 -C build
tar -xzvf R-4.0.2.tar.gz -C build
tar -xjvf xz-5.2.3.tar.bz2 -C build
tar -xzvf zlib-1.2.11.tar.gz -C build

# Begin the building of the sources
echo "Building dependencies"
cd build
echo "Building bzip2"
if [ -d bzip2-1.0.6 ]; then
    cd bzip2-1.0.6
    make install PREFIX=${R_BASE}

else
    echo "bzip2 failed to install"
fi

cd ..
echo "Building curl"
if [ -d curl-7.56.1 ]; then
    cd curl-7.56.1
    ./configure --prefix=${R_BASE} --without-libssh2
    make && make install

else
    echo "curl failed to install"
fi

cd ..
echo "Building pcre"
if [ -d pcre-8.41 ]; then
    cd pcre-8.41
    ./configure --prefix=${R_BASE} --enable-utf8 --enable-unicode-properties
    make && make install

else
    echo "pcre failed to install"
fi

cd ..
echo "Building xz"
if [ -d xz-5.2.3 ]; then
    cd xz-5.2.3
    ./configure --prefix=${R_BASE}
    make && make install

else
    echo "xz failed to install"
fi

cd ..
echo "Building zlib"
if [ -d zlib-1.2.11 ]; then
    cd zlib-1.2.11
    ./configure --prefix=${R_BASE}
    make && make install

else
    echo "zlib failed to install"
fi

cd ..
echo "Finished building dependencies"
echo "Now building R 4.0.2"

export CPATH=${CPATH}:${R_BASE}/include
export CPATH=${CPATH}:${R_BASE}/include/curl
export CPATH=${CPATH}:${R_BASE}/include/lzma
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${R_BASE}/lib

if [ -d R-4.0.2 ]; then
    cd R-4.0.2
    ./configure PKG_CONFIG_PATH="${R_BASE}/lib/pkgconfig" \
        CPPFLAGS="-I/${R_BASE}/include -I/${R_BASE}/include/curl -I/${R_BASE}/include/lzma" \
        LDFLAGS="-L/${R_BASE}/lib" --prefix=${R_BASE}
    make && make install

else
    echo "R 4.0.2 failed to build"
fi

cd ${R_BASE}
echo "Testing R 4.0.2"
if [ -x ./bin/R ]; then
    ./bin/R --version
    echo "R 4.0.2 has been successfully installed!"
    echo "You can now use R 4.0.2!"
    echo -e "\nCleaning up!"
    cd ${BASE}
    rm -rf ${R_TMP}

else
    echo "R failed to install correctly"
    echo "Please contact the i-ASK center at iask@ics.psu.edu for help"
fi

# Set up the local R module for the users to use
echo -e "\nSetting up R 4.0.2 module file"
cd ${BASE}
mkdir -p modules/r
cd modules/r && touch 4.0.2.lua

# Add relevant lua code to 4.0.2.lua
echo "help([[R is a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS.]])" >> 4.0.2.lua
echo "whatis('Description: R version 4.0.2')" >> 4.0.2.lua
echo "whatis('URL: https://www.r-project.org/')" >> 4.0.2.lua

# Set up paths for module
MODULE_PATH="prepend_path(\"PATH\", \"${R_BASE}/bin\")"
MODULE_CPATH="prepend_path(\"CPATH\", \"${R_BASE}/include\")"
MODULE_LD_PATH="prepend_path(\"LD_LIBRARY_PATH\", \"${R_BASE}/lib:${R_BASE}/lib64\")"
MODULE_MAN="prepend_path(\"MANPATH\", \"${R_BASE}/man:${R_BASE}/share/man\")"

echo ${MODULE_PATH} >> 4.0.2.lua
echo ${MODULE_CPATH} >> 4.0.2.lua
echo ${MODULE_LD_PATH} >> 4.0.2.lua
echo ${MODULE_MAN} >> 4.0.2.lua

cd ${BASE}
echo "Module file has been set up in ${BASE}/modules/r/4.0.2.lua"
echo -e "\nTo use R 4.0.2 module, use the following commands in your terminal:"
echo -e "\nmodule use ${BASE}/modules"
echo "module load r/4.0.2"
echo -e "\nShould you run into any issue please contact"
echo "The i-ASK center at iask@ics.psu.edu"
echo -e "\nAll done!"
