#!/bin/bash

# Create sw directory if it doesn't exist
if [ ! -d ${HOME}/work/sw ]; then
    mkdir -p ${HOME}/work/sw
fi

# Create modules directory if it doesn't exist
if [ ! -d ${HOME}/work/sw/modules ]; then
    mkdir -p ${HOME}/work/sw/modules
fi

# Extract julia binary and set up module file
mkdir -p ${HOME}/work/sw/modules/julia
tar -xzvf ./src/julia-1.5.3-linux-x86_64.tar.gz -C ${HOME}/work/sw
cp ./1.5.3-local.lua ${HOME}/work/sw/modules/julia/1.5.3-local.lua

# Adjust permissions accordingly
chmod -R ug+rx ${HOME}/work/sw/modules/julia

# Once the install is finished
echo "Installation of the julia 1.5.3 module has finished"
echo -e "\nTo use julia 1.5.3, enter the following commands in your terminal:\n"
echo "module use ~/work/sw/modules"
echo "module load julia/1.5.3-local"
echo -e "\nIf you run into any issues please contact Jason at iask@ics.psu.edu"
