#!/bin/bash

# Create sw7 directory if it doesn't exist
# sw7 means that this software will only
# work on the RHEL7 nodes
if [ ! -d ${HOME}/work/sw7 ]; then
    mkdir -p ${HOME}/work/sw7
fi

# Create modules directory if it doesn't exist
if [ ! -d ${HOME}/work/sw7/modules ]; then
    mkdir -p ${HOME}/work/sw7/modules
fi

# Create CLIMB directory under sw7
if [ ! -d ${HOME}/work/sw7/CLIMB ]; then
    mkdir -p ${HOME}/work/sw7/CLIMB
fi

# Extract julia binary and set up module file
mkdir -p ${HOME}/work/sw7/modules/climb
cp ./climb.sif ${HOME}/work/sw7/CLIMB/climb.sif
cp ./local.lua ${HOME}/work/sw7/modules/climb/local.lua

# Adjust permissions accordingly
chmod -R ug+rx ${HOME}/work/sw7/modules/climb

# Once the install is finished
echo -e "\nInstallation of the CLIMB module has finished"
echo -e "\nTo use CLIMB, enter the following commands in your terminal:\n"
echo "module use ~/work/sw7/modules"
echo "module load climb/local"
echo -e "\nIf you run into any issues please contact Jason at iask@ics.psu.edu"
echo -e "\nImportant: The CLIMB module will only function correctly on RHEL7 nodes!"
